{
  # Import all your configuration modules here
  imports = [
    ./bufferline.nix
    ./clipboard.nix
    ./cmp.nix
    ./diagnostics.nix
    ./flash.nix
    ./formatting.nix
    ./gitsigns.nix
    ./grug-far.nix
    ./hardtime.nix
    ./heirline.nix
    ./incline.nix
    ./lsp.nix
    ./markdown.nix
    ./noice.nix
    ./opencode.nix
    ./options.nix
    ./resession.nix
    ./snacks.nix
    ./supermaven.nix
    ./tasks.nix
    ./terminal.nix
    ./tokyonight.nix
    ./treesitter.nix
    ./which-key.nix
    ./windows.nix
    ./yazi.nix
  ];
}
