name: Nix Flake Update
on:
  schedule:
    - cron: 0 8 * * * # 3:00 AM CST
jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Update Flake
        run: |
          nix flake update
          nix flake check
      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add flake.lock
          git commit -m "Update flake.lock"
          git push
